---
- hosts: 172.31.19.174
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create a folder
    file:
      path: /home/ubuntu/myfolder
      state: directory

  - name: copy a file from master to node
    copy:
      src: my2file.txt
      dest: /home/ubuntu/my2file

  - name: move a file from master to node
    copy:
      src: my3file.txt
      dest: /home/ubuntu/myfolder/my3file

  - name: install apache2
    apt:
      name: apache2
      state: present

  - name: download internet file
    get_url:
      url: https://cf-templates-1xcq7h5f4509f-us-east-2.s3.us-east-2.amazonaws.com/20222166LY-myvpc.war
      dest: /home/ubuntu/20222166LY-myvpc.war
      force_basic_auth: yes

  - name: copy dynamic file to node side
    template:
      src: index.j2
      dest: /var/www/html/index.html

  handlers:
  - name: restart webserver
    service:
      name: apache2
      state: restarted







