---
- hosts: 172.31.19.174
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create a folder
    file:
      path: /home/ubuntu/myfolder
      state: directory

  - name: copy a file from master to node
    copy:
      src: my2file.txt
      dest: /home/ubuntu/my2file

  - name: move a file from master to node
    move:
      src: my3file.txt
      dest: /home/ubuntu/myfolder/my3file